### ISSUE TITLE
Settings screen unavailable via CRT?

### ISSUE THREAD

**Issue by coderkind** [theypsilon/Update_All_MiSTer#101]
Hi. I'm trying to enter the settings screen by holding UP on my controller as I launch the script, but it doesn't seem to have any effect. The update script runs as usual.

Wanted to see if there was a way to correct errors I'm getting with missing .zip files when trying to run some games (e.g. Gang Wars).

**Comment by theypsilon** [comment]
Hey! Scripts not showing on CRTs is a current limitation of the MiSTer ecosystem.
