### ISSUE TITLE
Feature: Additional third party scripts

### ISSUE THREAD

**Issue by theypsilon** [theypsilon/Update_All_MiSTer#11]
They should be from a trusted source.

**Comment by edru** [comment]
Opened a separate request before I noticed this one - but figured I copy/paste that in here too if you want the other closed.

Wondering if you could add the option to add the installer script for RetroSpy as an option to update? It is an input display reader that currently supports USB reading - hopefully SNAC soon. I created the script, all it does is download the file to the SD card - no logic in it at the moment, but thought it would be a cool optional add on.

https://github.com/retrospy/RetroSpy/tree/master/MiSTer

**Comment by theypsilon** [comment]
Right now I'm leaning more towards not implementing this feature, since I think is best to focus in cores basic setup, at least for now. But If I will consider it if I come back to this issue in the future.

Thanks for contributing with your script and your project.

**Comment by edru** [comment]
@theypsilon definitely makes sense to get the core out of the way first. I wish i had the chops to code that project myself, but it is a friend (zoggins) that is actually heading that project.

Look forward to seeing what this whole setup becomes. I feel like this is the true unifying script for MiSTer, and will eventually cater to anything needed.

**Comment by theypsilon** [comment]
Closing by now, I might reopen later
