### ISSUE TITLE
Request: Add RetroSpy db as an option

### ISSUE THREAD

**Issue by 40wattrange** [theypsilon/Update_All_MiSTer#111]
Worked with zoggins and we created the following database to replace the current method he was using for updates.

[retrospy/retrospy-MiSTer]
db_url = https://raw.githubusercontent.com/retrospy/retrospy-MiSTer/db/db.json.zip

Just filing this request as you asked us to let you know if we got a working DB up and running (on twitter) so you could add it as an option.

It is just referencing an external file from the latest release of RetroSpy as a whole.

Tested:
Initial download if nothing is preset works
Running updater again notices nothing new is preset
When a new release was put out, but nothing changed in the RetroSpy file itself, it did not download

Untested:
A new release in which the actual RetroSpy file has changed - as that hasn't happened since the db was created.

**Comment by theypsilon** [comment]
Added option at https://github.com/theypsilon/Update_All_MiSTer/commit/09732e7c05f5b3b5a00d3d1639fe674fb685c268

As I said in the public post on Patreon, thanks for pulling the strings!
