### ISSUE TITLE
Option to turn off cheats

### ISSUE THREAD

**Issue by dfilskov** [theypsilon/Update_All_MiSTer#112]
Excellent work - much appreciated! :)

Please consider an option to turn off cheats for us who never use them (and perhaps palettes/filters/shadow masks and other unnecssary "extras" too)

Cheers!

**Comment by theypsilon** [comment]
There isn't option in the UI yet (if that's what you mean), but you can disable cheats by modifying downloader.ini

Add this line under [MiSTer]:

```filter = !cheats```
