### ISSUE TITLE
Is the path wrong or changed?

### ISSUE THREAD

**Issue by szuping** [theypsilon/Update_All_MiSTer#118]
Recently unable to connect https://github.com/Toryalai1/MiSTer_ArcadeDatabase/db/mad_db.json.zip
The path should be wrong, the correct path is https://github.com/Toryalai1/MiSTer_ArcadeDatabase/tree/db/mad_db.json.zip
But I can't find how to set the path.

**Comment by nickxcom** [comment]
I am having the same error, or appears to be the same error

**Comment by jimbo-on-travels** [comment]
![2024-04-14-092658_1920x1080_scrot](https://github.com/theypsilon/Update_All_MiSTer/assets/166957029/dae7a358-cce8-4f2f-8617-f9125032d48a)
looks like Arcade database link is in these two locations and needs updating

**Comment by theypsilon** [comment]
It's fixed now
