### ISSUE TITLE
Massive numbers of MAME ROMs aren't being found

### ISSUE THREAD

**Issue by dowdle** [theypsilon/Update_All_MiSTer#119]
I set up a fresh MiSTer image this week and update_all with everything turned on... pulled down 200+ ROMs.  Comparing that to my second system, there are 600+ ROMs.  For whatever reason, and I tried multiple times over several days... the downloading of a significant number of ROMs isn't working.  Sorry to be vague by not providing specifics but I'm sure it is easily reproducable.

I did notice that it includes the Pac-Mania ROM from jotego that was just added recently.

**Comment by gavinpaul6707** [comment]
Hi there, I’m having the exact same issues. I’m setting up a larger sd card and after running update all it’s only pulling 200 compared to 600ish from my last sd card.

**Comment by j8ming** [comment]
I encountered the same problem

**Comment by metronik89** [comment]
Yup, having the same issue. Roms got deleted from the repo. A fix is being worked on thanks to the amazing dev team.

**Comment by dowdle** [comment]
I think this is fixed now.  I'm setting up two new MiSTer FPGA microSD cards sometime today and will find out for sure.

**Comment by dowdle** [comment]
On the cards I setup today, update_all pulled down approximately 612 .zip files to games/mame/ so it appears to have been resolved.  Thanks for your support.
