### ISSUE TITLE
Users report update_all script deletes cores

### ISSUE THREAD

**Issue by anderse77** [theypsilon/Update_All_MiSTer#124]
Please make sure this script obeys the CRUD principle. This script needs to do the following.
1. Download new cores.
2. For each core in the script core list, check if core repo exists.
If it exists and is of newer version than version if mister, update it.
If it does not exist, notify user and leave core on mister untouched. 

Please make sure that this script cannot delete cores!

**Comment by theypsilon** [comment]
This tool is syncing with what the creator chooses to publish. By using the database of some creator, you're trusting in their maintenance. If they choose to remove something, they might have a pretty good reason! Ask them! And remember that they are doing all this work for free!

In any case, read the documentation of Downloader, and check the options you may add to downloader.ini:
![image](https://github.com/theypsilon/Update_All_MiSTer/assets/852246/c4b14e20-b5cc-4f6a-bd15-a24f7b257162)
