### ISSUE TITLE
mame rom for super xevious missing file 

### ISSUE THREAD

**Issue by bnice** [theypsilon/Update_All_MiSTer#125]
Hi,

The mame rom for super xevious  (from my digging it appears to use the xevious mame rom) missing file " xv3_6.3j". Maybe need to move the rom download to different version number of the mame rows? I see in the script it does download certain roms from different versions numbers of mame.

**Comment by theypsilon** [comment]
Hey, if this is causing any trouble as in a game not running at all, please report it here: https://github.com/zakk4223/ArcadeROMsDB_MiSTer
