### ISSUE TITLE
Feature Request: Please have the update all download the GETTER Scripts & _arcade-organizer 

### ISSUE THREAD

**Issue by MAME-GETTER** [theypsilon/Update_All_MiSTer#2]
Please have the update_all.sh script download the following scripts to the "Scripts" Directory: 

https://github.com/MAME-GETTER/MiSTer_MAME_SCRIPTS/raw/master/update_mame-getter.sh 

https://github.com/MAME-GETTER/MiSTer_MAME_SCRIPTS/raw/master/update_hbmame-getter.sh

https://github.com/MAME-GETTER/_arcade-organizer/raw/master/update_arcade-organizer.sh

Thanks!

**Comment by MAME-GETTER** [comment]
I can add these actions to the scripts if need be. Let me know.

**Comment by theypsilon** [comment]
Sounds good.

Yes, you can add it. I'm busy right now with the MRA optimization.

Could you please put them behind a flag like all the others updaters?

Default to true, something like ADDITIONAL_SCRIPTS="true"

**Comment by theypsilon** [comment]
This will be done in those scripts.
