### ISSUE TITLE
Request: Add RetroSpy installer

### ISSUE THREAD

**Issue by edru** [theypsilon/Update_All_MiSTer#20]
Wondering if you could add the option to add the installer script for RetroSpy as an option to update? It is an input display reader that currently supports USB reading - hopefully SNAC soon. I created the script, all it does is download the file to the SD card - no logic in it at the moment, but thought it would be a cool optional add on.

https://github.com/retrospy/RetroSpy/tree/master/MiSTer

**Comment by theypsilon** [comment]
Will be discussed here #11
