### ISSUE TITLE
Suggestion: SCUMMVM support

### ISSUE THREAD

**Issue by mrsilva** [theypsilon/Update_All_MiSTer#26]
I'd like to suggest the Update_All script support installing and updating SCUMMVM for Mister.

**Comment by theypsilon** [comment]
Hi @mrsilva , thank you for your suggestion. But I'm personally not convinced about covering things that are not FPGA cores, or other things that are not included in the official MiSTer-devel updater. Still, if a lot of people want this I might reconsider it in the future, so I'll let this open.

**Comment by theypsilon** [comment]
I'm closing this now as it's out of the scope.
