### ISSUE TITLE
Request: have script create TGFX16-CD folder

### ISSUE THREAD

**Issue by birdybro** [theypsilon/Update_All_MiSTer#29]
Currently the script ran on a fresh image does not make a TGFX16-CD folder, and thus the BIOS-getter gives an error. Can we get an addition to the script that makes this folder if not present?

I will also suggest to the Mr. Fusion installer that they add this folder, since it's pretty standardly used.

**Comment by theypsilon** [comment]
I guess in case we really need this I could change that in the BIOS-getter itself. I will investigate this issue. Thanks for the feedback.

**Comment by theypsilon** [comment]
I was checking that I didn't get errors in various setups, I still need to test a fresh start though (I tested cleaning all cores, but not an empty SD card).

**Comment by theypsilon** [comment]
The solution I took is not creating the TGFX16-CD until there is a TGFX16 folder created, that way it doesn't error during the BIOS Getter. The TGFX16 folder should be created by MiSTer-devel updater anyways.
