### ISSUE TITLE
Jotego updater not downloading Popeye mra or core

### ISSUE THREAD

**Issue by xtcrefugee** [theypsilon/Update_All_MiSTer#31]
I've just run a full update from scratch, and the Jotego portion of the updater doesn't seem to be grabbing the Popeye core or mra.

I have CORE_CATEGORY_PATHS["arcade-cores"]="/media/fat/_Arcade/_Jotego" in my update_jtcores.ini if that makes any difference.

**Comment by theypsilon** [comment]
Jotego decided to leave Popeye to the other dev, so he removed the link from the wiki: https://github.com/jotego/jtbin/wiki

AFAIK, the popeye core maintained right now is this one: https://github.com/MiSTer-devel/Arcade-Popeye_MiSTer

**Comment by xtcrefugee** [comment]
Ah OK! That makes sense.
