### ISSUE TITLE
Question about the PC Updater Scripts

### ISSUE THREAD

**Issue by RetroDriven** [theypsilon/Update_All_MiSTer#32]
Is it possible to have everything Download to a specfic location or BASE_PATH? It looks like it defaults to ../ but I was wondering if it's possible to use the INI or some other way to Specifiy an Alternate Directory. I tried a few things with no luck so far.

**Comment by theypsilon** [comment]
I don't think so, but I haven't tested that scenario yet.

It would be nice if you can make a PR with that. Just try to be careful to not break other environments.

**Comment by theypsilon** [comment]
No further activity nor request in a year.
