### ISSUE TITLE
PC Updater - Linux Issue

### ISSUE THREAD

**Issue by RetroDriven** [theypsilon/Update_All_MiSTer#35]
I may be doing something wrong on my end but no matter what INI Settings I use it seems to ignore them and use the defaults. For example if I add `UNOFFICIAL_UPDATER="true" to the INI it doesn't work and seems to use the default "false" value. If I use the same INI settings and use the Windows Batch script within Windows it will work as expected.
`

**Comment by iGom** [comment]
I've got the exact same isssue,  update_all_linux.sh ignores update.ini entirely, but shows that it has read the file.

![image](https://user-images.githubusercontent.com/4786772/123515726-e75df680-d698-11eb-8864-7b6e0138118c.png)

**Comment by theypsilon** [comment]
PC Updater will be reworked with a Python version eventually.
