### ISSUE TITLE
Update_all script overwrites my setting in update.ini

### ISSUE THREAD

**Issue by jayp76** [theypsilon/Update_All_MiSTer#38]
I have a custon config in update.ini. When i choose to use the Mister update in update_all, it overwrites my custom config with an empty file. If the i add my custom config again and start the updater, it still makes a full resinc, which i don't want, i wann only the cores that are defined in my custom config.

**Comment by theypsilon** [comment]
Thanks for the report @jayp76 

I would like to ask you a few more questions.

Is this a long lasting issue, or you've noticed it only today?
When did you start using Update All approximately?

**Comment by jayp76** [comment]
I use the update_all script about 2 months, but used only for jotego and mame updates. This was the first time i used it with update script and update.ini.

**Comment by theypsilon** [comment]
I see. Could you please share the update_all.ini file? Maybe I can get some clues from there.

**Comment by jayp76** [comment]
Here you are. Had to rename the file to upload it.

[update_all.ini.txt](https://github.com/theypsilon/Update_All_MiSTer/files/5943457/update_all.ini.txt)

**Comment by theypsilon** [comment]
It doesn't seem to be strange at all. Could you please also share your update.ini and the log of a run where this problem happens? You will find the log from your latest run at /media/fat/Scripts/.cache/update_all/update_all.log

**Comment by jayp76** [comment]
I don't have the original update.ini, since it was nuked by the updater. I can only attach the one i had to create new, to update the cores. Unfortunately i don't have the log file when the problem occured. I'll try to reproduce it. For now, here is the update.ini is use.
[update.ini.txt](https://github.com/theypsilon/Update_All_MiSTer/files/6235922/update.ini.txt)

**Comment by theypsilon** [comment]
Hey @jayp76 , did your update.ini file got overwritten again?

**Comment by jayp76** [comment]
i have no time testing or using the MiSTer at the moment. If you like you can close the issue. If it occurs again i would open up a new issue.
