### ISSUE TITLE
Can't display the SETTINGS screen because fb terminal is off.

### ISSUE THREAD

**Issue by Saroumane** [theypsilon/Update_All_MiSTer#39]
Hello, I try to run Update_all_Mister directly from ssh like this : 
```
$ ssh root@a.b.c.d "cd /media/fat/Scripts/ && ./update_all.sh"
Password: 
Downloading
https://github.com/theypsilon/Update_All_MiSTer

Executing 'Update All' script
The All-in-One Updater for MiSTer
Version 1.3

Reading INI file './update_all.ini':
OK.

Sequence:
- Main Updater: MiSTer-devel
- Jotego Updater
- Unofficial Updater
- BIOS Getter
- MAME Getter
- HBMAME Getter
- Arcade Organizer

SORRY!
Can't display the SETTINGS screen because fb terminal is off.
Maybe you have fb_terminal=0 on MiSTer.ini?
NOTE: It could still work if you also add the following lines in MiSTer.ini:
    [Menu]
    vga_scaler=1

Start time: Sun Jan 31 16:25:26 UTC 2021

```

So : the script runs normally after skipping the settings menu : ` SORRY! Can't display the SETTINGS screen because fb terminal is off.`
I guess I have to modify a variable before running ssh ? Or run ssh with a special parameter ?
Or maybe a setting from my terminal emulator ? (I use Gnome Terminal 3.38 with bash)

**Comment by theypsilon** [comment]
Hello. The shell needs to be interactive, therefore I recommend you to run it in three steps:

1. ssh root@a.b.c.d
2. export TERM=xterm
3. cd /media/fat/Scripts/ && ./update_all.sh

**Comment by Saroumane** [comment]
Oh you are so right, I forgot I can't interact with a menu in a non-interactive shell.
But as long as I don't need to, the rest of the script carries on nicely.
Menu set aside, you really think there are other parts of the scripts that need an interactive shell ?

**Comment by theypsilon** [comment]
Nope, I can't think on any other part requiring an interactive shell.

**Comment by Saroumane** [comment]
Thanks for your quick answer.
