### ISSUE TITLE
download folder

### ISSUE THREAD

**Issue by juri74** [theypsilon/Update_All_MiSTer#41]
i have sd with system files (rbf, mra's and so on) and usb ssd drive containing only games folder, the script always download the mame rom on sd card creating another games folder

**Comment by theypsilon** [comment]
Hi!

For your use case you need to write:
1. `ROMMAME="/media/usb0/games/mame"` in the file /media/fat/Scripts/update_mame-getter.ini
2. `ROMHBMAME="/media/usb0/games/hbmame"` in the file /media/fat/Scripts/update_hbmame-getter.ini

That way you would have the mame roms in your ssd.

**Comment by juri74** [comment]
thank you again for your help

**Comment by Veridor** [comment]
@juri74 did that fix your issue? I'm running into a similar problem.
