### ISSUE TITLE
Sega System 1 alternatives are missing

### ISSUE THREAD

**Issue by mapfde** [theypsilon/Update_All_MiSTer#48]
Hi,

update_all includes the "alternatives" for the existing arcade cores. But the alternatives for SEGA System 1 are missing. They are available here: https://github.com/eubrunosilva/MiSTerMRA/blob/master/MRA/MRA_system1_0218_CRC_20200204.zip

**Comment by theypsilon** [comment]
Good to know, I didn't know about that repo, I will pull some strings.

Thank you

**Comment by theypsilon** [comment]
They are now in MiSTer-devel
