### ISSUE TITLE
line 3 BASE_PATH: unbound variable error

### ISSUE THREAD

**Issue by kinnonyee-armory** [theypsilon/Update_All_MiSTer#49]
I believe it has something to do with the 3rd line of the update_all.ini file that's generated

`ADDITIONAL_REPOSITORIES+=( "https://github.com/MiSTer-devel/Fonts_MiSTer|pf|$BASE_PATH/font" )`

It looks like this got generated because I didn't have a fonts directory beforehand, and hadn't downloaded the fonts.  Unsure if it's a pre-requisite before starting the process, as I didn't see it there.

After I did so, I still got the unbound variable error.  I deleted the ini and it generated again properly. This time, the file didn't have that line.  

Suggestion would be to have a better error message for that, and also to make a pre-requisite in your readme to need the fonts to be installed

**Comment by theypsilon** [comment]
Hi @kinnonyee-armory , Update All doesn't generate any file containing `ADDITIONAL_REPOSITORIES`.

It only generates an update_al.ini containing 4 variables when the script is run for first time, and there was no other update_all.ini file in the system previously. These 4 variables: 
![image](https://user-images.githubusercontent.com/852246/123525210-48a0bc80-d6cf-11eb-9d97-727af071e6f3.png)

I think you might have installed that update_all.ini file from somewhere else.

Also, `ADDITIONAL_REPOSITORIES` is only used by the regular updater. So any error reporting related to it would come from there.

Thanks for reporting issues, I'm sorry that it took me a while to see this one, but it's always greatly appreciated seeing some feedback from the user point of view.
