### ISSUE TITLE
mame updater seems to not update properly

### ISSUE THREAD

**Issue by jsmolina** [theypsilon/Update_All_MiSTer#50]
I've seen that on jotego's updates, new roms are not updated properly and it always requires to get into the console and delete them manually.

It might be caused by wrong dates? 

Maybe it's enough to provide a 'force mame full update' option somewhere.

**Comment by theypsilon** [comment]
Hey, I will take a look to see if I can reproduce that error.

But in the Settings Screen you can go to the MAME Getter submenu and there clean the mame folder. That way you will force a full update.

**Comment by theypsilon** [comment]
Didn't hear about this problem in a while, closing.
