### ISSUE TITLE
Add support for more unofficial cores (mandelbrot)

### ISSUE THREAD

**Issue by Mellified** [theypsilon/Update_All_MiSTer#52]
There are a few fun and interesting FPGA cores for MiSTer that are available - but not included in the unofficial core updater.

https://github.com/d18c7db/Gauntlet_FPGA
https://github.com/jacquesdriessen/MiSTer-mandelbrot

**Comment by theypsilon** [comment]
Hey, Gauntlet is already on MiSTer-devel. And about mandelbrot, I'm not sure it would be what the users of the unofficial updater are looking for. I'm trying to be very selective there, otherwise there would be many more unofficial cores being downloaded, but of course, I'm open to include if enough people show interest for it. I'll let this ticket open to see if there are more people asking for it.

Thanks for the suggestions!

**Comment by Mellified** [comment]
Update_all does not include or update the Gauntlet SVGA rbf located here:
https://github.com/d18c7db/Gauntlet_FPGA/tree/master/MiSTer/doc/svga

**Comment by Mellified** [comment]
> I'm trying to be very selective there, otherwise there would be many more unofficial cores being downloaded

The discoverability of unofficial cores is very poor. Including more unofficial cores enables users to explore additional uses for the MiSTer. It brings more attention to and support for the developers. More developers means more cores and features, which is good for the platform.

Users who aren't interested can turn off the unofficial core updater.

If there's still a concern, separate the unofficial updater into two parts - unofficial and "obscure" or "even more unofficial" options. Leave the "obscure" option off by default. At least then there's some ability to find these lesser known cores.

**Comment by theypsilon** [comment]
I've just added a way to include additional collections thanks to the downloader.

More info here: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/custom-databases.md

Hopefully somebody could maintain a better collection of unofficial cores this way. If a trusted collection of that sort gets good traction in the MiSTer ecosystem, I will include it as an option in Update All.
