### ISSUE TITLE
Jotego Updater does not download beta cores or MRA, even though "Install Beta Cores" is true

### ISSUE THREAD

**Issue by polyh3dron** [theypsilon/Update_All_MiSTer#57]
Install Beta Cores is set to "true".
A full resync has been forced.
The INI file has been cleared/deleted, and settings re-entered.
Clear All Cores option in update_all has been used so all cores and MRAs were deleted before the most recent attempt.
The Jotego Updater is still only downloading public cores and MRAs for me. No beta cores or MRAs.

**Comment by theypsilon** [comment]
Are you running update_all from ssh and staying on /root ?
In that case you would have to go first to /media/fat/Scripts
Will handle this better in the future: https://github.com/theypsilon/Update_All_MiSTer/issues/56

**Comment by sigboe** [comment]
@theypsilon Cant you just do this in the beginning of the updater

```bash
scriptdir="$(dirname "$(readlink -f "${0}")")"
pushd "${scriptdir}"
```

or use `scriptdir="$(dirname "$(readlink -f "${0}")")"` and refrence ini files as "${scriptdir}/file.ini" ?

**Comment by theypsilon** [comment]
> 
> 
> @theypsilon Cant you just do this in the beginning of the updater
> 
> ```shell
> scriptdir="$(dirname "$(readlink -f "${0}")")"
> pushd "${scriptdir}"
> ```
> 
> (also maybe for cleanliness sake add `popd` to the end of the script or exit routine)
> 
> or use `scriptdir="$(dirname "$(readlink -f "${0}")")"` and refrence ini files as "${scriptdir}/file.ini" ?

Yes, something like this is planned to be added. Is not as straight forward because there is something in place doing that already, and it shouldn't conflict.

**Comment by sigboe** [comment]
pushd works like a stack, so it should not interfere?

**Comment by theypsilon** [comment]
> 
> 
> pushd works like a stack, so it should not interfere?

I know, I use pushd in most of my scripts, including this one. But path resolution is not trivial in some places, and the changes have to be thoroughly tested before releasing an update.

**Comment by sigboe** [comment]
Good on you for testing thoroughly. Just want to say I have had great success in using `scriptdir="$(dirname "$(readlink -f "${0}")")"
` to determin the location of my scripts. Even with symlinks

**Comment by polyh3dron** [comment]
> Are you running update_all from ssh and staying on /root ?
> In that case you would have to go first to /media/fat/Scripts
> Will handle this better in the future: #56

Yes, I am running this from SSH and staying in /root.

**Comment by theypsilon** [comment]
This should be working now as discussed here.

**Comment by polyh3dron** [comment]
Thanks!
