### ISSUE TITLE
Mame and Hbmame saves Location

### ISSUE THREAD

**Issue by diettelo** [theypsilon/Update_All_MiSTer#58]
Can this script be so editable that users can chnage save location for mame and hbmame roms?

i tried many tes but something is in the script that allways downloads it on sd card.

**Comment by theypsilon** [comment]
You should be able to do it by modifying the following INI files:   `update_mame-getter.ini` and `update_hbmame-getter.ini`

Just put `ROMMAME="/your/path"` in the first and `ROMHBMAME="/your/path"` in the second.

Let me know if this works for you.

**Comment by theypsilon** [comment]
Keep in mind that MiSTer looks for the roms on the `mame` and `hbmame` directories placed here:

![image](https://user-images.githubusercontent.com/852246/126059760-b98d0985-4b92-4a26-a7d1-fb83b42dcbcd.png)

**Comment by diettelo** [comment]
Yes it did work.

But here comes the funny part:

It takes like about 2 minutes allways
when checking and skipping mame getter script.

On Micro sd save path very fast skip and on usb save path very long.

Its a fast drive so i dont get it.

hbmame skips in fast as allways.
