### ISSUE TITLE
Add option to update time w/ RTC script

### ISSUE THREAD

**Issue by 40wattrange** [theypsilon/Update_All_MiSTer#59]
Possible to have an option that would run the rtc script?

**Comment by marceloMedeiros** [comment]
+1 on this, since update_all and downloader both fail to run and give a false no internet error if the date/time is not set.

**Comment by theypsilon** [comment]
The new launchers (from this week) attempt to fix the date, so there shouldn't be errors unless the NTP server is not reachable, in which case the RTC script wouldn't work either.
