### ISSUE TITLE
update_all script issue

### ISSUE THREAD

**Issue by RyuTatakai** [theypsilon/Update_All_MiSTer#60]
When i try to run the update_all script i have this issue: 

curl: (35)error:1408D07B:SSL routines:ss13_get_key_exchange:bad signature 

@theypsilon @frederic-mahe

**Comment by theypsilon** [comment]
Is this something happening just recently? Are you on wifi, or with lan cable?

**Comment by RyuTatakai** [comment]
I received my Mister Fpga this friday , and tried to run the script for the
first time but it didn't work. I'm using a lan cable, i can see the ip
address and the time zone. I tried with a new sd card but i have the same
issue...

**Comment by theypsilon** [comment]
Have you tried to run any other script other than update_all? With which result?

**Comment by RyuTatakai** [comment]
i checked security_fixes, update, update_all , blisster_updater scripts and
they are not working too unfortunately. It seems my mister cannot download
anything .

**Comment by theypsilon** [comment]
There might be some problem with your cable, or with your de10-nano. I would try to talk with the store where you bought it.

**Comment by RyuTatakai** [comment]
Ok i'll do that, thanks you.
