### ISSUE TITLE
_9999 Year Games in Arcade Organizer?

### ISSUE THREAD

**Issue by KremlingKuthroat19** [theypsilon/Update_All_MiSTer#69]
Your new update_all script is great! Just ran it this morning. The only question I have is regarding the Arcade Organizer. In the _3 Collections and _3 By Year folders, there's another folder titled _9999. I'm assuming this is where MRAs that don't have a specified year are placed. I know that Space Race is a 1973 game for example. I'm just curious about this. Is it a bug?

Here's a list of the MRAs that appear in the _9999 year folder:
-1943 The Battle of Midway
-Action Fighter (World, S16A) [FD1089A 317-0018]
-Ares no tsubasa
-Clean Sweep
-Combat School Joystick
-Contra (US - Asia, set 1)
-Exed Exes
-Manhattan 24 Bunsyo (J)
-MX5000
-Space Race [TTL]
-Super Glob (Pac-Man, German) [bl]
-The Speed Rumbler (set 1)
-Zig Zag (Dig Dug Conversion) [bl]

**Comment by theypsilon** [comment]
This is probably missing metadata in the metadata repository: https://github.com/misteraddons/MiSTer_Arcade_MAD
