### ISSUE TITLE
🐛  Update All Script fails to download files and has lots of timeouts

### ISSUE THREAD

**Issue by shanytc** [theypsilon/Update_All_MiSTer#71]
I used the latest version of update_all.sh today, and it seems like there is a big timeouts issues when downloading from archive.org. lots of 409 and https issues.

<img src="https://preview.redd.it/sp2t11ppqho71.jpg?width=960&crop=smart&auto=webp&s=0799499839379bc107965f1976e8a8188779594b"/>

**Comment by theypsilon** [comment]
Could you please try again, it seems archive.org had some hickups for a while

**Comment by shanytc** [comment]
> Could you please try again, it seems archive.org had some hickups for a while

Yeah now it's working.
