### ISSUE TITLE
REGION_OTHER name mismatch

### ISSUE THREAD

**Issue by zakk4223** [theypsilon/Update_All_MiSTer#72]
update_all script writes the ini file setting as 'REGION_OTHER', but the arcade organizer 2.0 script is looking for 'REGION_OTHERS' and falling back to the default of ONLY_IN_OWN_FOLDER

**Comment by theypsilon** [comment]
Thanks, that was a very good catch. Fixed here: https://github.com/theypsilon/Update_All_MiSTer/commit/c0dad998c53f208f4f41cd3f290d006d2d8896fa
