### ISSUE TITLE
INI file warning triggers due to filesystem case insensitivity

### ISSUE THREAD

**Issue by zakk4223** [theypsilon/Update_All_MiSTer#73]
See this thread: https://misterfpga.org/viewtopic.php?f=27&t=3388

cd /media/fat/scripts will result in pwd being '/media/fat/scripts' because that value isn't based on the canonical name on the filesystem, it's (more or less) based on what the provided path was. 

Probably need to either use readlink -f to detect the actual path $PWD/ini_filename.ini resides at, or maybe just use /bin/pwd instead of the shell built in

**Comment by theypsilon** [comment]
Thanks for reporting this! It should be fixed now.
