### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by jimmyc802** [theypsilon/Update_All_MiSTer#78]
New to MiSTer so I may be doing something dumb here. When I try running update_all, I get a FileNotFoundError. Full log attached and ini attached.

FileNotFoundError: [Errno 2] No such file or directory: '/media/fat//Scripts/.config/downloader/downloader.log'
mv: cannot stat '/media/fat/Scripts/.config/downloader/downloader.log': No such file or directory

[update_all.log](https://github.com/theypsilon/Update_All_MiSTer/files/7826533/update_all.log)
[update_all.ini.txt](https://github.com/theypsilon/Update_All_MiSTer/files/7826540/update_all.ini.txt)

**Comment by dragonvenenoso** [comment]
Go into Misc and disable "Use new Downloader" :)

**Comment by theypsilon** [comment]
The bug is already fixed. If you run it, it should work fine now. Thanks for reporting it!

**Comment by jimmyc802** [comment]
Fantastic! Thank you for the quick response.
