### ISSUE TITLE
Missing BIOS files with network drive at /media/fat/cifs

### ISSUE THREAD

**Issue by JosVerheij** [theypsilon/Update_All_MiSTer#84]
The `cifs` directory in `/media/fat` takes precedence over /media/fat/games when the former is mounted. Ie. when you have a network drive mounted at `/media/fat/cifs`, MiSter will load e.g. SNES games from `/media/fat/cifs/SNES`, as opposed to the standard `/media/fat/games/SNES`.

The `update_all` script --and specifically the BIOS Getter-- does not seem to take this into account. This results in missing (e.g.) `boot.rom` files.

When running `update_all`, files are downloaded to `/media/fat/games/`, even when `/media/fat/cifs` should be used.

**Comment by theypsilon** [comment]
BIOS Getter takes that into account. Is the experimental bios database the one that doesn't do that yet (I'm working on it). Are you using that one?

**Comment by JosVerheij** [comment]
Good to know! In my case it was the PSX boot.rom that wasn't placed within the cifs folder. I'll try to reproduce it with other core files.

**Comment by JosVerheij** [comment]
I miscomprehended PSX support, because apparently the BIOS Getter does not support that core yet. Tested with NeoGeo and MegaCD and it worked excellently.

Verry sorry for wasting your time.
