### ISSUE TITLE
Add Test builds download

### ISSUE THREAD

**Issue by ThetaX55** [theypsilon/Update_All_MiSTer#85]
Would be cool if it automatically downloaded test builds. Make a test core folder..

They need a way to put more then 1 mister file and have a option to load it. There are some test mister files that may interfere with future cores when updated for a test core. Thats for another guy thou maybe.

**Comment by theypsilon** [comment]
There is some experimental solution for that already outside of Update All. You may check it in following post: https://www.patreon.com/posts/59518589
