### ISSUE TITLE
JTSTABLE link in the main Readme.md points to an invalid address

### ISSUE THREAD

**Issue by Drakonas** [theypsilon/Update_All_MiSTer#88]
Jotego has restructured the two release repos to be jtbin and jtcores_mister.

[https://github.com/jotego/jtcores_mister](https://github.com/jotego/jtcores_mister) should be the correct address for the new stable location.

I based this info from how jotego's latest update_jtcores.sh script chooses what repos to download from with your script.

**Comment by theypsilon** [comment]
Done, thank you!
