### ISSUE TITLE
Gameboy palettes for Adventure Vision, Supervision and Gamate

### ISSUE THREAD

**Issue by ajgowans** [theypsilon/Update_All_MiSTer#89]
The Adventure Vision, Supervision and Gamate cores also use the Gameboy palettes.  Currently to utilise this you need to manually copy those palette folders to the game folders for those three other systems.  

Is it possible to have a symlink added to each folder so it points to the Gameboy folder when the palettes option is selected from the system OSD menu?  If not, is it possible to also download the Gameboy palettes folders to those systems game folders as well?

Note: unsure if this should be done by Downloader or Update All

**Comment by theypsilon** [comment]
Hey, thanks for the suggestion. This should be included in Adventure Vision, Supervision and Gamate repositories, under a **Palette** folder as you may see on Gameboy repository.
