### ISSUE TITLE
games directories not created when running update

### ISSUE THREAD

**Issue by deelowe** [theypsilon/Update_All_MiSTer#90]
The following directories should be created under games when running the update script, but are not.

- Arduboy
- Apple-I
- Chip8
- GameOfLife
- PDP1

**Comment by theypsilon** [comment]
Apple-I and PDP1 are fixed now.
Arduboy, Chip8, and GameOfLife belong to the "Other" folder; therefore, there are no default games folders for them. Should Arduboy and Chip8 belong to another category? You could open an issue in Wiki_MiSTer about that. What about GameOfLife? Why does it need a default games folder?
