### ISSUE TITLE
[request] Option to grab dual ram PSX core in place of default single RAM

### ISSUE THREAD

**Issue by 40wattrange** [theypsilon/Update_All_MiSTer#92]
I know Robert is releasing dualram versions in the test-builds channel of the MiSTer discord - I'm not sure there is another repository out there, but if so, would it be possible to add an option to grab it in place of the singleram version?

**Comment by theypsilon** [comment]
I talked to him about this, and he prefers to see the single ram version as the only official version for widespread usage. Thus it would not be appropriate to facilitate grabbing that version from my side. If somebody does a DB to integrate it in downloader.ini, it could still be used with update_all, but I won't be doing it or adding it to the menus.
