### ISSUE TITLE
Option to download only some roms instead of all of them

### ISSUE THREAD

**Issue by ProxyCell** [theypsilon/Update_All_MiSTer#95]
Hi,

I don't want this to sound like a complaint as this script is very useful to me.
I'd just like to request a feature to either select/whitelist/blacklist games to download as over time it will just grow and scrolling through so many is already a bit long.

Thanks for the great work done with this project.

**Comment by theypsilon** [comment]
Hey, thanks for the support.

This is already possible. Check this: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/download-filters.md.

For example, if you add `!arcade-asteroids` to your mister filters, you'd avoid downloading its Asteroids MRAs and ROMs.
