### ISSUE TITLE
[request] Option to download MikeS's Y/C cores

### ISSUE THREAD

**Issue by matijaerceg** [theypsilon/Update_All_MiSTer#98]
Would be great if there was a way to use update_all.sh to download [MikeS's Y/C cores](https://github.com/MikeS11/MiSTerFPGA_YC_Encoder/tree/main/YC%20Builds) and put them in their own subfolder (like Console_YC). Currently the only way to do it is manually.

Ideally there would be a way to filter these as well (or at least use the downloader.ini filter)

**Comment by theypsilon** [comment]
I'm open to that. But the author @MikeS11 or another contributor must offer a downloader database so that I can integrate it in update_all

It's effortless to do, following these steps: https://github.com/theypsilon/DB-Template_MiSTer

**Comment by MikeS11** [comment]
Ill try to work on it this weekend :).

**Comment by theypsilon** [comment]
Great, don't hesitate to ping me if you need any sort of help https://discord.gg/bfs248Rm

**Comment by MikeS11** [comment]
https://github.com/MikeS11/YC_Builds-MiSTer

Done

**Comment by theypsilon** [comment]
Added
