### ISSUE TITLE
Latest update_all version doesn't save menu settings

### ISSUE THREAD

**Issue by mlc4050** [theypsilon/Update_All_MiSTer#99]
After changing menu settings, saving, and exiting update_all, none of the menu settings after saved when relaunching the script.

**Comment by theypsilon** [comment]
Do you observe any changes in the downloader.ini file? Is it a file that you can edit manually?

**Comment by javier-rodas** [comment]
I see the same behaviour here.

Starting from a clean environment:
1. Remove /media/fat/downloader.ini
2. Launch update_all => it creates a default downloader.ini. By default it has these 3 sections enabled:
```
[distribution_mister]
db_url = https://raw.githubusercontent.com/MiSTer-devel/Distribution_MiSTer/main/db.json.zip

[jtcores]
db_url = https://raw.githubusercontent.com/jotego/jtcores_mister/main/jtbindb.json.zip

[atrac17/Coin-Op_Collection]
db_url = https://raw.githubusercontent.com/atrac17/Coin-Op_Collection/db/db.json.zip
```
3. Then you press UP, enable/disable some sections (ie I disable all and enable the "Arcade ROMs Database".
4. Save and Exit => It run correctly with only the ROM downloader.

If you see the resulting downloader.ini it's now:
```
[arcade_roms_db]
db_url = https://raw.githubusercontent.com/theypsilon/ArcadeROMsDB_MiSTer/db/arcade_roms_db.json.zip
```

The issue appears when you launch update_all again, and it shows that you have **4 (four) sections enabled** (the three default sections and the new "Arcade ROMs Database" we have previously enabled). So, it's not correctly identifying the missing [distribution_mister], [jtcores] and [atrac17/Coin-Op_Collection] sections at downloader.ini file to DISABLE them.

**Comment by theypsilon** [comment]
I've fixed this, and now it should reproduce the behavior you describe. Thanks a lot for your detailed report!
